version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./Comparator w- files on Static.postman_collection.json
          environment: ./mnfst.postman_environment.json
